# Project information
site_name: CERTUS TAP
site_description: Certus AI
site_url: https://mharrod.github.io/certustap/
site_author: Martin Harrod
copyright: © Copyright 2025 Martin Harrod.

# Repository information
repo_name: mharrod/certustap
repo_url: https://github.com/mharrod/certustap
edit_uri: edit/main/docs/ 

# Theme
theme:
  icon:
      repo: fontawesome/brands/github-alt
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  custom_dir: overrides
  palette:
    - scheme: default
      primary: certus   # defined via CSS variables in your assets/stylesheets/*.css
      accent: certus
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: certus
      accent: certus
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - content.action.edit      # “Edit this page”
    # - content.action.view      # “View source”
    # - content.action.history   # “Page history”
    # - navigation.expand  # Disable default expand to allow collapsible dropdowns

# Extra assets
extra_css:
  - assets/stylesheets/main.css
  - assets/stylesheets/footer.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/javascripts/tables.js
  - assets/javascripts/nav-toggle.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: ./docs
      check_paths: true

  # ✅ Enable Mermaid rendering support
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Plugins
plugins:
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
      strict: false
  - search
  - exclude:
      glob:
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
  # - git-revision-date-localized:
  #     enable_creation_date: false


