name: Publish docs (MkDocs → GitHub Pages)

on:
  push:
    branches: [ "main" ]          # change if your default branch differs
  workflow_dispatch:

# Required for the official Pages actions
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Configure Poetry
        run: |
          poetry --version
          poetry config virtualenvs.in-project true
          poetry env use 3.12

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py312-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-py312-

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          # Ensure MkDocs + plugins are in the SAME Poetry venv (safe no-ops if already present)
          poetry run pip install --upgrade mkdocs mkdocs-material mkdocs-exclude

      - name: Build site
        run: poetry run mkdocs build --strict

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site   # MkDocs output dir

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
