name: Publish docs (MkDocs)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Configure Poetry
        run: |
          poetry --version
          poetry config virtualenvs.in-project true
          poetry env use 3.12

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py312-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-py312-

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          # Ensure MkDocs + plugins are present in the Poetry venv (safe no-ops if already installed)
          poetry run pip install mkdocs mkdocs-material mkdocs-exclude --upgrade --quiet

      - name: Build site
        run: poetry run mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
          # cname: docs.example.com
